### ISSUE TITLE
Suggest alternative usage to typed splices

### ISSUE THREAD

**Issue by chshersh** [snoyberg/githash#10]
Currently `haskell-src-exts` library can't parse typed splices:

* https://github.com/haskell-suite/haskell-src-exts/issues/278

Because of that HLint breaks on `$$tGitInfoCwd` usages:

* https://github.com/ndmitchell/hlint/issues/186

Fortunately, there's alternative way of using `tGitInfoCwd` which doesn't break `hlint`. What we ended up doing in our project is the following trick:

```haskell
let gi = $(unType <$> Git.tGitInfoCwd) in ...
```

It doesn't look like fixing this bug is a priority in `haskell-src-exts`. So, for me it makes sense to tell about this trick so `githash` library can be adopted easier.

**Comment by snoyberg** [comment]
I'm not sure what you're asking for here. Is this a doc improvement, or exposing something else. I'd be OK with a PR going in either direction.

**Comment by ChShersh** [comment]
@snoyberg I'm talking about documentation improvement. Sorry if I wasn't clear enough. But I'm not sure what is the best place to put this documentation note.

**Comment by snoyberg** [comment]
I'd guess module documentation. Personally I think this is an edge enough case that I wouldn't bother, but happy to take a PR.

**Comment by snoyberg** [comment]
Closing due to lack of progress

**Comment by chshersh** [comment]
@snoyberg Sure, no problem! My main motivation for this issue was `hlint` behavior without an obvious fix. But new `hlint` uses GHC parser and handles this case correctly :ok_hand:
