### ISSUE TITLE
runGit fails when git is not on path

### ISSUE THREAD

**Issue by dbaynard** [snoyberg/githash#7]
This is from stack:

```
Exception when trying to run compile-time code:
        git: readCreateProcessWithExitCode: runInteractiveProcess: exec: does not exist (No such file or directory)
      Code: tGitInfoCwdTry
```

https://github.com/snoyberg/githash/blob/c3d38598bd625b2882db77f92d05109003d9bd10/src/GitHash.hs#L184-L189

It looks like readCreateProcessWithExitCode is throwing an exception when it can't find `git`. ~~It would help to say that explicitly — perhaps by catching and rethrowing with a better error message?~~

Edit: This needs to be handled so `tGitInfoCwdTry` doesn't throw an exception.

Related: commercialhaskell/stack#4364

**Comment by snoyberg** [comment]
This should be addressed by https://github.com/snoyberg/githash/commit/48f0c952a5076b50cfd172bff14d4f7431a0a9a3, I'll drop a comment on the Stack issue. Thanks for clarifying 👍

**Comment by snoyberg** [comment]
I've made a release with the new fixes, closing.
