### ISSUE TITLE
Doesn't work with cabal new-build

### ISSUE THREAD

**Issue by DanBurton** [snoyberg/githash#9]
I haven't taken a close look, but I'm pretty sure https://github.com/DanBurton/yesod-gitrev/issues/4 is due to githash not working with `cabal new-build`. I have no idea what the fix is.

Here's the relevant error message from yesod-gitrev's ExampleMain.

```
examples/ExampleMain.hs:27:30: error:
    • Exception when trying to run compile-time code:
        GHEGitRunFailed "." ["rev-parse","--show-toplevel"] (ExitFailure 128) "" "fatal: not a git repository (or any of the parent directories): .git\n"
      Code: tGitRev
    • In the Template Haskell splice $$(tGitRev)
      In the first argument of ‘Master’, namely ‘$$(tGitRev)’
      In the second argument of ‘($)’, namely ‘Master $$(tGitRev)’
   |
27 | main = warp 3000 $ Master $$(tGitRev)
   |                              ^^^^^^^
```

**Comment by snoyberg** [comment]
One of the problems with the gitrev package is that it silently fails when Git information isn't available, as opposed to githash which actually reports the error. Are you sure that this was ever working in the past? It seems likely that this is a bug/change of behavior in new-build, the built example never had the correct information, and githash is simply demonstrating the already present bug.

**Comment by DanBurton** [comment]
Sorry, to be clear, I don't believe this was ever working with `cabal new-build` in the past.
(Broken w/ both gitrev and githash.)
Agree that actually reporting the error is preferable.

I believe this is intentional on the part of new-build: to isolate sources from any outside inputs. Wondering what the solution/workaround is. Likely involves either a patch to new-build or extra work from users to add something to their .cabal file.

I don't expect you to solve it, just letting you know the issue exists.

**Comment by DanBurton** [comment]
One potential solution we have the power to enact here would be a new splice that produces a `Maybe GitInfo`, so that the caller can decide how to address absence of the info. This still sucks for users of new-build since they get `Nothing`.

**Comment by snoyberg** [comment]
Thanks for the clarifications, that makes sense. If this is how new-build works, it's fairly surprising to me. At least in the Yesod world we do a lot of stuff with reading files via TH at compile time, and that relies on having the correct working directory set.

**Comment by snoyberg** [comment]
Planning on leaving this as-is, closing
